"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, CheckCircle2, CircleDot, Gauge, RefreshCw, Siren, TableProperties } from "lucide-react";
import { AppShell, Badge, Card, Unavailable } from "@loupe/ui";

type TableHealth={table_id:string;status:"healthy"|"degraded"|"critical"|"unknown";freshness_minutes:number|null;active_incident_count:number};
type Incident={incident_id:string;table_id:string;check_type:string;severity:string;status:string;created_at:string;observed_value:number|null;expected_value:number|null;affected_metrics:string[];owner:string|null;next_allowed_statuses:string[]};
type Warehouse={generated_at:string;dataset:string;monitored_tables:number;healthy_tables:number;degraded_tables:number;critical_tables:number;open_incidents:number;freshness_minutes:number|null;tables:TableHealth[];incidents:Incident[]};
type TriageView = "warehouse" | "sourceHealth" | "incidentQueue";

export default function Page(){
  const api=process.env.NEXT_PUBLIC_API_BASE_URL??"http://localhost:8000";
  const [data,setData]=useState<Warehouse|null>(null);const [error,setError]=useState<string|null>(null);const [loading,setLoading]=useState(true);const [selected,setSelected]=useState<Incident|null>(null);const [notes,setNotes]=useState("");const [transitioning,setTransitioning]=useState(false);
  const [activeView,setActiveView]=useState<TriageView>("warehouse");
  const load=useCallback(()=>{setLoading(true);setError(null);fetch(`${api}/api/v1/triage/warehouse`).then(async r=>{if(!r.ok)throw new Error();return r.json()}).then((result:Warehouse)=>{setData(result);setSelected(current=>current?result.incidents.find(i=>i.incident_id===current.incident_id)??null:result.incidents[0]??null)}).catch(()=>setError("Persisted warehouse health could not be reached. No fictional incidents were substituted.")).finally(()=>setLoading(false));},[api]);
  useEffect(load,[load]);
  const healthyPct=data?.monitored_tables?Math.round(data.healthy_tables/data.monitored_tables*100):0;
  async function transition(target:string){if(!selected)return;if(target==="resolved"&&!notes.trim()){setError("Resolution notes are required before resolving an incident.");return}setTransitioning(true);setError(null);try{const response=await fetch(`${api}/api/v1/triage/incidents/${encodeURIComponent(selected.incident_id)}/transition`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({target_status:target,expected_current_status:selected.status,resolution_notes:target==="resolved"?notes:null})});if(!response.ok)throw new Error();setNotes("");await load()}catch{setError("The incident changed or the transition could not be committed. Refresh and retry.")}finally{setTransitioning(false)}}
  const nav = [
    {label:"Warehouse",icon:Gauge,active:activeView==="warehouse",onClick:()=>setActiveView("warehouse")},
    {label:"Source Health",icon:TableProperties,active:activeView==="sourceHealth",onClick:()=>setActiveView("sourceHealth")},
    {label:"Incident Queue",icon:Siren,active:activeView==="incidentQueue",onClick:()=>setActiveView("incidentQueue")},
  ];
  return <AppShell active="triage" brand="Triage" brandIcon={Activity} navigation={nav}>
    <div className="dashboard-surface">
      <header className="hero-panel page-header"><div><div className="eyebrow">RELIABILITY LAYER</div><h1>Warehouse health</h1><div className="muted">Persisted incidents across governed data sources</div></div><div className="actions"><Badge>{data?`${data.monitored_tables} sources monitored`:"Live persistence"}</Badge><button className="button" onClick={load} disabled={loading}><RefreshCw size={15}/>{loading?"Refreshing…":"Refresh"}</button></div></header>
      {error&&<Unavailable message={error}/>} {loading&&!data?<div className="card skeleton" aria-label="Loading warehouse health"/>:data&&<>
        {activeView==="warehouse"&&<section><div className="section-title">Key metrics</div><div className="metric-grid"><Stat label="Healthy tables" value={String(data.healthy_tables)} detail={`${healthyPct}%`}/><Stat label="Open incidents" value={String(data.open_incidents)} detail={`${data.critical_tables} critical`}/><Stat label="Sources healthy" value={`${healthyPct}%`} detail={`${data.monitored_tables} governed`}/><Stat label="Max freshness" value={formatFreshness(data.freshness_minutes)} detail="metadata"/></div></section>}
        {activeView==="sourceHealth"&&<section><div className="section-title">Operations</div><div className="triage-layout"><Card><div className="card-head"><div><h2>Governed source health</h2><div className="muted small">Current persisted incident state</div></div><Badge>Live</Badge></div><div className="health-bars">{data.tables.map(table=><button key={table.table_id} className="health-row" onClick={()=>setSelected(data.incidents.find(i=>i.table_id===table.table_id)??null)}><span className="health-name">{table.table_id}</span><span className="health-track"><span className={`health-fill health-${table.status}`} style={{width:table.status==="healthy"?"100%":table.status==="degraded"?"62%":table.status==="critical"?"35%":"18%"}}/></span><span className={`status-dot status-${table.status}`}>{table.status}</span></button>)}</div></Card><Card><div className="card-head"><div><h2>Incident timeline</h2><div className="muted small">{selected?`${selected.table_id} · ${selected.check_type}`:"No active incident selected"}</div></div>{selected&&<Badge tone="warning">{selected.severity}</Badge>}</div>{selected?<><div className="timeline"><TimelineStep icon={CircleDot} label="Detected" detail={new Date(selected.created_at).toLocaleString()}/><TimelineStep icon={CheckCircle2} label={selected.status} detail={selected.owner?`Owner: ${selected.owner}`:"Owner unassigned"}/>{selected.affected_metrics.length>0&&<TimelineStep icon={AlertTriangle} label="Affected metrics" detail={selected.affected_metrics.join(", ")}/>}</div><div className="incident-actions">{selected.next_allowed_statuses.map(status=><button className="button" key={status} disabled={transitioning} onClick={()=>transition(status)}>{status.replaceAll("_"," ")}</button>)}</div>{selected.next_allowed_statuses.includes("resolved")&&<textarea className="notes" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Required resolution notes" aria-label="Resolution notes"/>}</>:<div className="empty-review"><CheckCircle2 size={24}/><strong>No active incidents</strong><span className="muted small">Governed sources currently have no persisted active incidents.</span></div>}</Card></div></section>}
        {activeView==="incidentQueue"&&<section><div className="section-title">Incident queue</div><Card><div className="card-head"><div><h2>Active incident queue</h2><div className="muted small">Prioritized by deterministic severity rules</div></div><Badge tone={data.incidents.length?"warning":"accent"}>{data.incidents.length} active</Badge></div>{data.incidents.length?<div className="table-wrap"><table className="data-table incident-table"><thead><tr><th>Severity</th><th>Incident</th><th>Affected metrics</th><th>Age</th><th>Status</th></tr></thead><tbody>{data.incidents.map(incident=><tr key={incident.incident_id} onClick={()=>setSelected(incident)} className={selected?.incident_id===incident.incident_id?"selected":""}><td><span className={`severity severity-${incident.severity}`}>{incident.severity}</span></td><td><strong>{incident.table_id}</strong><div className="muted small">{incident.check_type.replaceAll("_"," ")}</div></td><td>{incident.affected_metrics.join(", ")||"None mapped"}</td><td>{formatAge(incident.created_at)}</td><td>{incident.status}</td></tr>)}</tbody></table></div>:<div className="queue-empty"><CheckCircle2 size={18}/>No active incidents</div>}</Card></section>}
      </>}
    </div>
  </AppShell>;
}
function Stat({label,value,detail}:{label:string;value:string;detail:string}){return <Card><div className="stat-label">{label}</div><div className="stat-line"><span className="stat-value">{value}</span><span className="delta">{detail}</span></div></Card>}
function TimelineStep({icon:Icon,label,detail}:{icon:typeof CircleDot;label:string;detail:string}){return <div className="timeline-step"><Icon size={17}/><div><strong>{label}</strong><div className="muted small">{detail}</div></div></div>}
function formatFreshness(value:number|null){if(value===null)return "Unknown";if(value<60)return `${Math.round(value)}m`;return `${Math.round(value/60)}h`}
function formatAge(created:string){const minutes=Math.max(0,Math.floor((Date.now()-new Date(created).getTime())/60000));return minutes<60?`${minutes}m`:`${Math.floor(minutes/60)}h ${minutes%60}m`}
